baseURL = "https://ghaadyy.github.io/"
languageCode = "en-us"
title = "Ghady Youssef"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML"]

[params]
  # Custom params if needed later

[module]
  [[module.mounts]]
    source = "assets"
    target = "static/assets"
  [[module.mounts]]
    source = "content/verification/google5698644fe4b56e15.html"
    target = "static/google5698644fe4b56e15.html"
